#include <iostream>
#include <string>

using namespace std;
int main(){
try {
	string ex;
	throw ex;
	try {

	} catch (string &e) {
		cout<<"Inside Inner class"<<endl;
	}
} catch (Exception e) {
}
return 0;
}
